### PR TITLE
Refactor Ledger Mutators and Tests

### PR DESCRIPTION
**Pull request by lasuk**
This PR is pure re-factoring. It does not change the functionality, but streamlines the code base such that new features and tests can be added with fewer code changes.

Change:
1. Extract method to map ledger entry (extracts duplicated code from add_ledger_entry in update_ledger_entry into a local function)
2. Streamline tests (clarify fixtures, define test data in a table, split long test functions into smaller steps, simplify checks)

The PR is best reviewed commit-by-commit.

### CODE REVIEW

**Comment by AlexTheWizardL** [comment]
All the changes look very neat to me. Thanks a lot for such a refactoring, these changes make our code cleaner and more readable.

I have one more suggestion for how we can increase code readability for our tests:

Let's create a function `compare_tnx()` that will be used to identify the created/updated txn and compare with expected
```python
def compare_tnx(id: int, remote: pd.DataFrame, target: pd.DataFrame, drop_id: bool = False):
    created = remote.loc[remote['id'] == str(id)].reset_index(drop=True)
    expected = StandaloneLedger.standardize_ledger(target).reset_index(drop=True)
    if drop_id:
        pd.testing.assert_frame_equal(created.drop(columns=['id']), expected.drop(columns=['id']))
    else:
        pd.testing.assert_frame_equal(created, expected)
```

Then we can replace this lines:
```python
    created = remote.loc[remote['id'] == str(id)].reset_index(drop=True)
    expected = StandaloneLedger.standardize_ledger(target).reset_index(drop=True)
    pd.testing.assert_frame_equal(created.drop(columns=['id']), expected.drop(columns=['id']))
```
with just a one line:
```python
compare_tnx(id=id, remote=remote, target=target, drop_id=True)
```

The same here:
```python
    updated = remote.loc[remote['id'] == str(id)].reset_index(drop=True)
    expected = StandaloneLedger.standardize_ledger(target).reset_index(drop=True)
    pd.testing.assert_frame_equal(updated, expected)
```
replace with:
```python
compare_tnx(id=id, remote=remote, target=target)
```

@lasuk Shout if you disagree or have other thoughts or suggestions

**Comment by lasuk** [comment]
> I have one more suggestion for how we can increase code readability for our tests:
> Let's create a function `compare_tnx()` that will be used to identify the created/updated txn and compare with expected
> 
> ```python
> def compare_txn(id: int, remote: pd.DataFrame, target: pd.DataFrame, drop_id: bool = False):
>     created = remote.loc[remote['id'] == str(id)].reset_index(drop=True)
>     expected = StandaloneLedger.standardize_ledger(target).reset_index(drop=True)
>     if drop_id:
>         pd.testing.assert_frame_equal(created.drop(columns=['id']), expected.drop(columns=['id']))
>     else:
>         pd.testing.assert_frame_equal(created, expected)
> ```
> [..snip..]

Extracting boiler-plate code that is repeated throughout the test unit and abstracting it in a helper function makes a lot of sense. On the other hand, helper functions that combine very specific tasks are not obvious to understand. All in all, they make the code appear simpler (the unit is now shorter) but the do not really make understanding simpler (the comparison logic is still the same, and is actually harder to understand now that it is hidden in some abstraction layer).

Btw: The helper function proposed above is actually quite complex. You can easily this if you attempt to describe its functionality:
1. subset remote, but not target data frame by id. 
2. standardize target but not remote data frame, 
3. reset index
etc.

**Comment by AlexTheWizardL** [comment]
> > I have one more suggestion for how we can increase code readability for our tests:
> > Let's create a function `compare_tnx()` that will be used to identify the created/updated txn and compare with expected
> > ```python
> > def compare_txn(id: int, remote: pd.DataFrame, target: pd.DataFrame, drop_id: bool = False):
> >     created = remote.loc[remote['id'] == str(id)].reset_index(drop=True)
> >     expected = StandaloneLedger.standardize_ledger(target).reset_index(drop=True)
> >     if drop_id:
> >         pd.testing.assert_frame_equal(created.drop(columns=['id']), expected.drop(columns=['id']))
> >     else:
> >         pd.testing.assert_frame_equal(created, expected)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [..snip..]
> 
> Extracting boiler-plate code that is repeated throughout the test unit and abstracting it in a helper function makes a lot of sense. On the other hand, helper functions that combine very specific tasks are not obvious to understand. All in all, they make the code appear simpler (the unit is now shorter) but the do not really make understanding simpler (the comparison logic is still the same, and is actually harder to understand now that it is hidden in some abstraction layer).
> 
> Btw: The helper function proposed above is actually quite complex. You can easily this if you attempt to describe its functionality:
> 
> 1. subset remote, but not target data frame by id.
> 2. standardize target but not remote data frame,
> 3. reset index
>    etc.

Then I think it's not worth doing to create this helper function

**Comment by lasuk** [comment]
Here's a more generic approach:

Extend `pandas.testing.assert_frame_equal()` with a options 'ignore_index' and 'ignore_columns', courtesy of ChatGPT
```python
def assert_frame_equal(left, right, *args, ignore_index=False, ignore_columns=None, **kwargs):
    """
    Compare two DataFrames for equality, with options to ignore index and specific columns.

    Parameters:
    left : DataFrame
        First DataFrame to compare.
    right : DataFrame
        Second DataFrame to compare.
    *args : tuple
        Additional positional arguments to pass to pandas.testing.assert_frame_equal.
    ignore_index : bool, default False
        Whether to ignore the index in the comparison.
    ignore_columns : list, default None
        List of column names to ignore (drop) in the comparison.
    **kwargs : additional keyword arguments
        Additional arguments to pass to pandas.testing.assert_frame_equal.
    """
    if ignore_index:
        left = left.reset_index(drop=True)
        right = right.reset_index(drop=True)
    
    if ignore_columns:
        left = left.drop(columns=ignore_columns, errors='ignore')
        right = right.drop(columns=ignore_columns, errors='ignore')
    
    assert_frame_equal(left, right, *args, **kwargs)
````

Then we can replace this lines:
```python
created = remote.loc[remote['id'] == str(id)].reset_index(drop=True)
expected = StandaloneLedger.standardize_ledger(target).reset_index(drop=True)
pd.testing.assert_frame_equal(created.drop(columns=['id']), expected.drop(columns=['id']))
```
with this one line:
```python
assert_frame_equal(remote, StandaloneLedger.standardize_ledger(target), ignore_index=True, ignore_columns=['id'])
```
The resulting line is longer than in your example above, but IMO easier to understand. 

@AlexTheWizardL: Your thoughts?

**Comment by lasuk** [comment]
Thanks a lot for enhancing the data frame test. Looks very good!

**Comment by lasuk** [comment]
I've further improved test readability and robustness in commit (look up ledger entries by 'id', rather than integer position.)

Btw: I learned about the query function, which is much more to my taste. I prefer
```python
df.query('id == 2')
```
over
```python
df.loc[df['id'] == 2]
```

**Comment by lasuk** [comment]
@AlexTheWizardL: Ready to merge from my side. Do you agree?

**Comment by AlexTheWizardL** [comment]
Yep, ready to merge

**Pull request merged**
